### ISSUE TITLE
Running app in Xcode and isDebug returning false.

### ISSUE THREAD

**Issue by efares** [mattlewis92/cordova-plugin-is-debug#2]
Hi,

I'm using `@ionic-native/is-debug: ^4.3.3` and running my mobile app on my iPad using Xcode and in my console log I am getting `Is debug: false`. The code I am using is:
```
// Check if device isDebug
      this.isDebug.getIsDebug().then(
        (isDebug: boolean) => {
          console.log('Is debug:', isDebug);
          this.debugOn = isDebug;
        }).catch((error: any) => console.error(error));
```
According to the [documentation](https://ionicframework.com/docs/native/is-debug/), It should return a promise that resolves with true if the app was installed via Xcode.

Am I missing something or is this an issue?

**Comment by mattlewis92** [comment]
I believe this is caused by the DEBUG flag being set to false in your xcode settings, https://github.com/mattlewis92/cordova-plugin-is-debug#caveats might help (I mostly just copied / pasted this code from a blog post and have no real experience with xcode / ios development so can't help any further I'm afraid)
